# This file was generated by GoReleaser. DO NOT EDIT.
class Edgr < Formula
  desc "edgr is a tool for downloading and persisting SEC EDGAR filings and data"
  homepage "https://github.com/piquette/edgr"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/piquette/edgr/releases/download/v0.0.1/edgr_0.0.1_darwin_amd64.tar.gz"
    sha256 "582deb4c70ae8f9b6ecdafbf475069eeb7da3aa879a77ed2be8fa0e408e1e9cc"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/piquette/edgr/releases/download/v0.0.1/edgr_0.0.1_linux_amd64.tar.gz"
      sha256 "c074b664dcbf954e6ea766fb945a90bb9158c78257ea3ec0a3e0386b019515f9"
    end
  end

  def install
    bin.install "bin/edgr"
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>KeepAlive</key>
    <dict>
      <key>SuccessfulExit</key>
      <false/>
    </dict>
    <key>Label</key>
    <string>#{plist_name}</string>
    <key>RunAtLoad</key>
    <true/>
    <key>WorkingDirectory</key>
    <string>#{var}</string>
    <key>StandardErrorPath</key>
    <string>#{var}/log/edgr.log</string>
    <key>StandardOutPath</key>
    <string>#{var}/log/edgr.log</string>
  </dict>
</plist>
  EOS
  end
end
